{"name": "test_register_user", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 'This username already exists.' but got: 'None'\nassert None == 'This username already exists.'", "trace": "browserInstance = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"b75bbee0a5a0f2a2e218e0d3259387e5\")>\n\n    @pytest.mark.smoke\n    def test_register_user(browserInstance):\n        driver = browserInstance\n        driver.get(\"https://parabank.parasoft.com/parabank/index.htm\")\n        browserInstance.maximize_window()\n        login_with_existing_user = existing_user(browserInstance)\n    \n        login_with_existing_user.click_on_register_page()\n        login_with_existing_user.first_name(user_data[\"user_first_name\"])\n        login_with_existing_user.last_name(user_data[\"user_second_name\"])\n        login_with_existing_user.address(user_data[\"user_address\"])\n        login_with_existing_user.city(user_data[\"user_city\"])\n        login_with_existing_user.state(user_data[\"user_state\"])\n        login_with_existing_user.zip_code(user_data[\"user_zip_code\"])\n        login_with_existing_user.phone(user_data[\"user_phone_no\"])\n        login_with_existing_user.ssn(user_data[\"user_ssn\"])\n        login_with_existing_user.user_name(user_data[\"user_name_1\"])\n        login_with_existing_user.password(user_data[\"user_password\"])\n        login_with_existing_user.confirm_password(user_data[\"user_confirm_password\"])\n        time.sleep(1)\n        login_with_existing_user.click_register()\n        time.sleep(4)\n        Existing_error_message = f\"This username already exists.\"\n    \n        # Assertion\n        existing_welcome_error_message = login_with_existing_user.existing_error_message()\n>       assert existing_welcome_error_message == Existing_error_message, \\\n            f\"Expected '{Existing_error_message}' but got: '{existing_welcome_error_message}'\"\nE       AssertionError: Expected 'This username already exists.' but got: 'None'\nE       assert None == 'This username already exists.'\n\nTests\\test_register_with_existing_user.py:43: AssertionError"}, "attachments": [{"name": "screenshot_on_failure", "source": "4d0b6eac-2ba7-4cb1-9bec-210dca3f254d-attachment.png", "type": "image/png"}], "start": 1758269336370, "stop": 1758269347065, "uuid": "9da8d3b8-a144-4b77-b953-2964521e9e7e", "historyId": "2ce22f22946577bf79898fe2febcfb5f", "testCaseId": "2ce22f22946577bf79898fe2febcfb5f", "fullName": "Tests.test_register_with_existing_user#test_register_user", "labels": [{"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_register_with_existing_user"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "8508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_register_with_existing_user"}], "titlePath": ["Tests", "test_register_with_existing_user.py"]}